global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@selextract.com'
  smtp_auth_username: 'alerts@selextract.com'
  smtp_auth_password: '${SMTP_PASSWORD}'

route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 5m
    - match:
        severity: warning
      receiver: 'warning-alerts'
      repeat_interval: 30m
    - match:
        severity: info
      receiver: 'info-alerts'
      repeat_interval: 12h
    - match:
        alertname: LowComputeUnitsRemaining
      receiver: 'business-alerts'
      repeat_interval: 24h

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://api:8000/alerts/webhook'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'alertmanager'
            password: '${ALERTMANAGER_WEBHOOK_PASSWORD}'

  - name: 'critical-alerts'
    email_configs:
      - to: '${ADMIN_EMAIL}'
        subject: '[CRITICAL] Selextract Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Instance: {{ .Labels.instance }}
          Started: {{ .StartsAt }}
          {{ end }}
        headers:
          priority: 'high'
    webhook_configs:
      - url: 'http://api:8000/alerts/webhook'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'alertmanager'
            password: '${ALERTMANAGER_WEBHOOK_PASSWORD}'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#alerts-critical'
        title: 'Critical Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          *Instance:* {{ .Labels.instance }}
          {{ end }}
        send_resolved: true

  - name: 'warning-alerts'
    email_configs:
      - to: '${ADMIN_EMAIL}'
        subject: '[WARNING] Selextract Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Instance: {{ .Labels.instance }}
          Started: {{ .StartsAt }}
          {{ end }}
    webhook_configs:
      - url: 'http://api:8000/alerts/webhook'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'alertmanager'
            password: '${ALERTMANAGER_WEBHOOK_PASSWORD}'

  - name: 'info-alerts'
    webhook_configs:
      - url: 'http://api:8000/alerts/webhook'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'alertmanager'
            password: '${ALERTMANAGER_WEBHOOK_PASSWORD}'

  - name: 'business-alerts'
    email_configs:
      - to: '${BUSINESS_EMAIL}'
        subject: '[BUSINESS] Selextract Notification: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          User ID: {{ .Labels.user_id }}
          Started: {{ .StartsAt }}
          {{ end }}
    webhook_configs:
      - url: 'http://api:8000/alerts/business-webhook'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'alertmanager'
            password: '${ALERTMANAGER_WEBHOOK_PASSWORD}'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
  - source_match:
      severity: 'warning'
    target_match:
      severity: 'info'
    equal: ['alertname', 'instance']

templates:
  - '/etc/alertmanager/templates/*.tmpl'