version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.40.0
    container_name: selextract-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2G'
        reservations:
          cpus: '0.5'
          memory: '1G'
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  grafana:
    image: grafana/grafana:9.2.0
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana.ini:/etc/grafana/grafana.ini:ro
    ports:
      - "3002:3001"
    networks:
      - monitoring
      - selectium-saas_selextract_internal
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1G'
        reservations:
          cpus: '0.2'
          memory: '512M'
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  alertmanager:
    image: prom/alertmanager:v0.25.0
    container_name: selextract-alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=http://localhost:9093'
      - '--web.route-prefix=/'
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - alertmanager_data:/alertmanager
    ports:
      - "9093:9093"
    networks:
      - monitoring
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '256M'
        reservations:
          cpus: '0.1'
          memory: '128M'
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9093/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3

  node-exporter:
    image: prom/node-exporter:v1.4.0
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      - '--web.disable-exporter-metrics'
      - '--collector.processes'
    volumes:
      # Windows-compatible volume mounts - limited but functional
      - type: tmpfs
        target: /host/proc
        tmpfs:
          size: 100M
      - type: tmpfs
        target: /host/sys
        tmpfs:
          size: 100M
      - type: tmpfs
        target: /rootfs
        tmpfs:
          size: 100M
    ports:
      - "9100:9100"
    networks:
      - monitoring
      - selectium-saas_selextract_internal
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '128M'
        reservations:
          cpus: '0.1'
          memory: '64M'
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9100/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.11.1
    environment:
      - DATA_SOURCE_NAME=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@selectium-saas_postgres_1:5432/${POSTGRES_DB}?sslmode=disable
      - PG_EXPORTER_EXTEND_QUERY_PATH=/etc/postgres_exporter/queries.yaml
    volumes:
      - ./postgres-queries.yaml:/etc/postgres_exporter/queries.yaml:ro
    ports:
      - "9187:9187"
    networks:
      - monitoring
      - selectium-saas_selextract_internal
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '128M'
        reservations:
          cpus: '0.1'
          memory: '64M'
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9187/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
    external_links:
      - selectium-saas_postgres_1:postgres

  redis-exporter:
    image: oliver006/redis_exporter:v1.45.0
    environment:
      - REDIS_ADDR=redis://:${REDIS_PASSWORD}@selectium-saas_redis_1:6379
    ports:
      - "9121:9121"
    networks:
      - monitoring
      - selectium-saas_selextract_internal
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '64M'
        reservations:
          cpus: '0.05'
          memory: '32M'
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9121/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
    external_links:
      - selectium-saas_redis_1:redis

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.10.0
    command:
      - '-nginx.scrape-uri=http://selectium-saas_nginx_1:8080/nginx_status'
    ports:
      - "9113:9113"
    networks:
      - monitoring
      - selectium-saas_selextract_internal
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '64M'
        reservations:
          cpus: '0.05'
          memory: '32M'
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9113/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
    external_links:
      - selectium-saas_nginx_1:nginx

  celery-exporter:
    image: danihodovic/celery-exporter:0.8.0
    environment:
      - CELERY_EXPORTER_BROKER_URL=redis://:${REDIS_PASSWORD}@selectium-saas_redis_1:6379/0
      - CELERY_EXPORTER_LISTEN_ADDRESS=0.0.0.0:9540
      - CELERY_EXPORTER_MAX_TASKS=10000
    ports:
      - "9540:9540"
    networks:
      - monitoring
      - selectium-saas_selextract_internal
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '128M'
        reservations:
          cpus: '0.1'
          memory: '64M'
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9540/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
    external_links:
      - selectium-saas_redis_1:redis

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  alertmanager_data:
    driver: local

networks:
  monitoring:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
  selectium-saas_selextract_internal:
    external: true